heat_template_version: queens

description: >
  OpenStack Octavia Worker service.

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  OctaviaAmphoraImageTag:
    default: 'amphora-image'
    description: Glance image tag for identifying the amphora image.
    type: string
  OctaviaAmphoraNetworkList:
    default: []
    description: List of networks to attach to amphorae.
    type: comma_delimited_list
  OctaviaAmphoraSshKeyName:
    type: string
    default: 'octavia-ssh-key'
    description: SSH key name.
  OctaviaLoadBalancerTopology:
    default: ''
    description: Load balancer topology configuration.
    type: string
  OctaviaFlavorId:
    default: 65
    description: Nova flavor ID to be used when creating the nova flavor for
                 amphora.
    type: number
  OctaviaTimeoutClientData:
    default: 50000
    description: Frontend client inactivity timeout.
    type: number
  OctaviaTimeoutMemberConnect:
    default: 5000
    description: Backend member connection timeout.
    type: number
  OctaviaTimeoutMemberData:
    default: 50000
    description: Backend member inactivity timeout.
    type: number
  OctaviaTimeoutTcpInspect:
    default: 0
    description: Time to wait for TCP packets for content inspection.
    type: number

conditions:
  octavia_topology_unset: {equals : [{get_param: OctaviaLoadBalancerTopology}, ""]}

resources:

  OctaviaBase:
    type: ./octavia-base.yaml
    properties:
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for Octavia controller services.
    value:
      service_name: octavia_controller
      config_settings:
        map_merge:
          - get_attr: [OctaviaBase, role_data, config_settings]
          - octavia::controller::amp_boot_network_list: {get_param: OctaviaAmphoraNetworkList}
            octavia::controller::amp_flavor_id: {get_param: OctaviaFlavorId}
            octavia::controller::amp_image_tag: {get_param: OctaviaAmphoraImageTag}
            octavia::controller::amp_ssh_key_name: {get_param: OctaviaAmphoraSshKeyName}
            octavia::controller::enable_ssh_access: true
            octavia::controller::timeout_client_data: {get_param: OctaviaTimeoutClientData}
            octavia::controller::timeout_member_connect: {get_param: OctaviaTimeoutMemberConnect}
            octavia::controller::timeout_member_data: {get_param: OctaviaTimeoutMemberData}
            octavia::controller::timeout_tcp_inspect: {get_param: OctaviaTimeoutTcpInspect}
          -
            if:
            - octavia_topology_unset
            - {}
            - octavia::controller::loadbalancer_topology: {get_param: OctaviaLoadBalancerTopology}

