heat_template_version: queens

description: >
  Configure tuned

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  TunedProfileName:
    default: ''
    description: Tuned Profile to apply to the host
    type: string
    tags:
      - role_specific
  TunedCustomProfile:
    default: ''
    description: The definition of a new tuned profile in INI format which
                 will be named after the TunedProfileName and applied to the
                 host. E.g. if TunedProfileName is 'my_profile', it creates
                 the file '/etc/tuned/my_profile/tuned.conf' on host whose
                 content is the value of TunedCustomProfile, e.g. "[main]\n
                 include=throughput-performance\n[sysctl]\nvm.dirty_ratio=10"
    type: string
    tags:
      - role_specific

outputs:
  role_data:
    description: Role data for tuned
    value:
      service_name: tuned
      config_settings:
        map_replace:
          - map_replace:
            - tripleo::profile::base::tuned::profile: TunedProfileName
              tripleo::profile::base::tuned::custom_profile: TunedCustomProfile
            - values: {get_param: RoleParameters}
          - values: {'TunedProfileName': {get_param: TunedProfileName},
                     'TunedCustomProfile': {get_param: TunedCustomProfile}}
      step_config: |
        include ::tripleo::profile::base::tuned
