resource_registry:
#  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/controller-custom.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/controller-custom.yaml
#  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/ceph-storage-custom.yaml
  OS::TripleO::NodeUserData: /home/stack/rhosp13/my-overcloud/swap.yaml
  OS::TripleO::Compute::Ports::ExternalPort: /home/stack/rhosp13/my-overcloud/network/ports/external.yaml
  OS::TripleO::NodeExtraConfigPost: /home/stack/rhosp13/nestedkvm.yaml
parameter_defaults:
  # Customize all these values to match the local environment
  InternalApiNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 192.168.122.0/24
  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  # Use an External allocation pool which will leave room for floating IPs
  ExternalAllocationPools: [{'start': '192.168.122.130', 'end': '192.168.122.150'}]
  InternalApiNetworkVlanID: 201
  StorageNetworkVlanID: 202
  StorageMgmtNetworkVlanID: 203
  TenantNetworkVlanID: 204
  ExternalNetworkVlanID: 100
  DnsServers: ["8.8.8.8","8.8.4.4"]
  EC2MetadataIp: 192.0.2.1
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.122.1
  ControlPlaneDefaultRoute: 192.0.2.1
  DnsServers: [ "8.8.8.8" ]
  # Customize bonding options if required (will be ignored if bonds are not used)
  BondInterfaceOvsOptions:
      "bond_mode=balance-tcp lacp=active other-config:lacp-fallback-ab=true"
  NovaComputeExtraConfig:
    nova::compute::reserved_host_memory: 512
    nova::config::nova_config:
      DEFAULT/instance_name_template:
        value: '%(hostname)s'
    nova::compute::libvirt::libvirt_cpu_mode: custom
    nova::compute::libvirt::libvirt_cpu_model: Westmere-IBRS
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: VMX
  ComputeExtraConfig:
    nova::config::nova_config:
      DEFAULT/instance_name_template:
        value: '%(hostname)s'
  CephAnsibleDisksConfig:
    devices:
    - /dev/vdb
    osd_scenario: collocated
#  CephPoolDefaultPgNum: 32
#  CephConfigOverrides:
#    ceph_pool_pg_num: 64
#    ceph_pool_pgp_nmum: 64
  CephPools:
    - name: volumes
      pg_num: 8
      size: 1
    - name: images
      pg_num: 8
      size: 1
    - name: backups
      pg_num: 8
      size: 1
    - name: vms
      pg_num: 8
      size: 1
    - name: metrics
      pg_num: 8
      size: 1
