resource_registry:
#  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/controller.yaml
#  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/rhosp13/my-overcloud/network/config/single-nic-vlans/ceph-storage.yaml
  OS::TripleO::NodeUserData: /home/stack/rhosp13/my-overcloud/swap.yaml
parameter_defaults:
  # Customize all these values to match the local environment
  InternalApiNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 192.168.122.0/24
  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  # Use an External allocation pool which will leave room for floating IPs
  ExternalAllocationPools: [{'start': '192.168.122.130', 'end': '192.168.122.150'}]
  InternalApiNetworkVlanID: 201
  StorageNetworkVlanID: 202
  StorageMgmtNetworkVlanID: 203
  TenantNetworkVlanID: 204
  ExternalNetworkVlanID: 100
  DnsServers: ["8.8.8.8","8.8.4.4"]
  EC2MetadataIp: 192.0.2.1
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.122.1
  ControlPlaneDefaultRoute: 192.0.2.1
  DnsServers: [ "8.8.8.8" ]
  # Customize bonding options if required (will be ignored if bonds are not used)
  BondInterfaceOvsOptions:
      "bond_mode=balance-tcp lacp=active other-config:lacp-fallback-ab=true"
  ControllerExtraConfig:
    tripleo::haproxy::haproxy_default_timeout: ['http-request 10s','queue 2m','client 2m','server 5m','check 10s']
    tripleo::haproxy::horizon::options:
      timeout: 'server 5m'
  NovaComputeExtraConfig:
    nova::compute::reserved_host_memory: 512
  ExtraConfig:
    snmp::ro_network: 10.0.0.0/8
    snmp::location: qai2
    snmp::contact: noc@expertcity.com
    tripleo::profile::base::snmp::snmpd_config:
      - 'createUser ro_snmp_user MD5 "786566a5b0f7092091b9684438606b7ce08798f2"'
      - 'rouser ro_snmp_user_tripleo'
      - 'proc  cron'
      - 'includeAllDisks  10%'
      - 'master agentx'
      - 'trapsink localhost public'
      - 'iquerySecName internalUser'
      - 'rouser internalUser'
      - 'defaultMonitors yes'
      - 'linkUpDownNotifications yes'
      - 'proc httpd'
      - 'proc heat-engine'
      - 'proc neutron-server'
      - 'proc rabbitmq-server'
      - 'proc haproxy'

