# A Heat environment file which can be used to enable a
# Cinder Pure Storage FlashArray iSCSI backend, configured via puppet
resource_registry:
  OS::TripleO::Services::CinderBackendPure: ../puppet/services/cinder-backend-pure.yaml

parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnablePureBackend: true
  CinderPureBackendName: 'tripleo_pure'
  CinderPureStorageProtocol: 'iSCSI'
  CinderPureSanIp: ''
  CinderPureAPIToken: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  CinderPureUseChap: false
  CinderPureMultipathXfer: true
  CinderPureImageCache: true
