resource_registry:
  OS::TripleO::SoftwareDeployment: ../config-download-structured.yaml
  OS::TripleO::StructuredDeployment: ../config-download-structured.yaml

  OS::Heat::SoftwareDeployment: ../config-download-software.yaml
  OS::Heat::StructuredDeployment: ../config-download-structured.yaml

  OS::TripleO::DeploymentSteps: OS::Heat::None

  OS::TripleO::Ssh::KnownHostsDeployment: OS::Heat::None
  OS::TripleO::Ssh::HostPubKey: OS::Heat::None

  OS::TripleO::HostPrepDeployment: OS::Heat::None

  # stable/queens fix to enable config-download for PreNetworkConfig
  OS::TripleO::Services::BootParams: ../extraconfig/pre_network/boot-params-service.yaml
  OS::TripleO::Reboot::SoftwareDeployment: OS::Heat::None
