---
fixes:
  - |
    OpenDaylight inactivity probe for setting the OVSDB timeout now defaults
    to 180s. This helps fix scale issues for large number of computes nodes
    in OpenDaylight deployments.
