heat_template_version: queens

description: >
  Template for nova-api's logging to files

parameters:
  DockerNovaApiImage:
    description: image
    type: string
  DeployIdentifier:
    default: ''
    type: string
    description: >
      Setting this to a unique value will re-run any deployment tasks which
      perform configuration on a Heat stack-update.

outputs:
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  volumes:
    description: The volumes needed to log to files in the host.
    value: &nova_api_volumes
      - /var/log/containers/nova:/var/log/nova
      - /var/log/containers/httpd/nova-api:/var/log/httpd
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      step_2:
        # db sync runs before permissions set by kolla_config
        nova_api_init_logs:
          image: {get_param: DockerNovaApiImage}
          privileged: false
          user: root
          volumes: *nova_api_volumes
          command: ['/bin/bash', '-c', 'chown -R nova:nova /var/log/nova']
          environment:
            # NOTE: this should force this container to re-run on each
            # update (scale-out, etc.)
            - list_join:
                - ''
                - - 'TRIPLEO_DEPLOY_IDENTIFIER='
                  - {get_param: DeployIdentifier}
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent directories
        file:
          path: "{{ item.path }}"
          state: directory
          setype: "{{ item.setype }}"
        with_items:
          - { 'path': /var/log/containers/nova, 'setype': svirt_sandbox_file_t }
          - { 'path': /var/log/containers/httpd/nova-api, 'setype': svirt_sandbox_file_t }
          - { 'path': /var/log/nova, 'setype': svirt_sandbox_file_t }
      - name: nova logs readme
        copy:
          dest: /var/log/nova/readme.txt
          content: |
            Log files from nova containers can be found under
            /var/log/containers/nova and /var/log/containers/httpd/nova-*.
        ignore_errors: true
